#!/usr/bin/env node
// Writes electron/build-config.js — a tiny script the renderer loads
// synchronously via <script src> before reactions-overlay.js. Avoids any
// timing race vs. main-process executeJavaScript injection. Also bakes the
// QR data URL so the projector never needs network to render its overlay.
const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');

const secret = process.env.APL_HOST_SECRET || '';
const apiBase = process.env.APL_API_BASE || 'https://apl-api.gdgbaroda.com';
const webUrl = process.env.APL_WEB_URL || 'https://apl.gdgbaroda.com';
const formUrl = process.env.APL_FORM_URL || 'https://forms.gle/pmgdS2ndkWfXu3Vf7';

async function bakeQr(url, width) {
  return QRCode.toDataURL(url, {
    errorCorrectionLevel: 'M',
    margin: 1,
    width,
    color: { dark: '#000000', light: '#ffffff' },
  });
}

async function main() {
  const qrDataUrl = await bakeQr(webUrl, 360);
  const formQrDataUrl = await bakeQr(formUrl, 720); // larger — full-screen view

  const cfg = secret
    ? { apiBase, hostSecret: secret, webUrl, qrDataUrl, formUrl, formQrDataUrl }
    : { webUrl, qrDataUrl, formUrl, formQrDataUrl };

  const out = path.join(__dirname, '..', 'electron', 'build-config.js');
  const body =
    `// generated by scripts/bake-config.cjs — do not edit\n` +
    `window.__APL__ = ${JSON.stringify(cfg)};\n`;
  fs.writeFileSync(out, body);
  console.log(secret ? 'Baked ' + out : 'Baked stub (no secret) ' + out);
}

main().catch((e) => { console.error(e); process.exit(1); });
