#!/usr/bin/env node
// Writes electron/build-config.js — a tiny script the renderer loads
// synchronously via <script src> before reactions-overlay.js. Avoids any
// timing race vs. main-process executeJavaScript injection. Also bakes the
// QR data URL so the projector never needs network to render its overlay.
const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');

const secret = process.env.APL_HOST_SECRET || '';
const apiBase = process.env.APL_API_BASE || 'https://apl-api.gdgbaroda.com';
const webUrl = process.env.APL_WEB_URL || 'https://apl.gdgbaroda.com';

async function main() {
  const qrDataUrl = await QRCode.toDataURL(webUrl, {
    errorCorrectionLevel: 'M',
    margin: 1,
    width: 360,
    color: { dark: '#000000', light: '#ffffff' },
  });

  const cfg = secret
    ? { apiBase, hostSecret: secret, webUrl, qrDataUrl }
    : { webUrl, qrDataUrl };

  const out = path.join(__dirname, '..', 'electron', 'build-config.js');
  const body =
    `// generated by scripts/bake-config.cjs — do not edit\n` +
    `window.__APL__ = ${JSON.stringify(cfg)};\n`;
  fs.writeFileSync(out, body);
  console.log(secret ? 'Baked ' + out : 'Baked stub (no secret) ' + out);
}

main().catch((e) => { console.error(e); process.exit(1); });
