#!/usr/bin/env node
// Writes electron/build-config.js — a tiny script the renderer loads
// synchronously via <script src> before reactions-overlay.js. This avoids
// any timing race vs. main-process executeJavaScript injection.
//
// In dev (no APL_HOST_SECRET), writes a stub that defines window.__APL__ = {}
// so the script tag doesn't 404; main.cjs still injects the real values from
// env at did-finish-load.
const fs = require('fs');
const path = require('path');

const secret = process.env.APL_HOST_SECRET || '';
const apiBase = process.env.APL_API_BASE || 'https://apl-api.gdgbaroda.com';

const cfg = secret ? { apiBase, hostSecret: secret } : {};
const out = path.join(__dirname, '..', 'electron', 'build-config.js');
const body = `// generated by scripts/bake-config.cjs — do not edit\nwindow.__APL__ = ${JSON.stringify(cfg)};\n`;
fs.writeFileSync(out, body);
console.log(secret ? 'Baked ' + out : 'Baked stub (no secret) ' + out);
